services:
  prom_test:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - prom_network
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./:/etc/prometheus
    networks:
      - prom_network
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - prom_network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  
networks:
  prom_network:
    driver: bridge